name: build-java
on: [push, pull_request]

jobs:
  build:
    runs-on:
    steps:
      - uses: actions/checkout@v2
      - name: set JDK17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: build test maven
        run: mvn --batch-mode --update-snapshots verify
