name: c-action
on: [push, pull_request]

jobs:
  testing:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install requirements
        run: |
          sudo apt -qq -y update
          sudo apt -qq install clang-tidy-10 clang-format-10
      - name: setup git spec
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: filename formatter
        run: |
          IFS=$'\n'
          for fname in `find . -type -f name '*.c' -o -name '*.h'`; do
            echo "${fname}"
            new_fname=`echo ${fname} | tr ' ' '_'`
            echo "    ${new_fname}"
            new_fname=`echo ${new_fname} | tr '-' '_'`
            echo "    ${new_fname}"
            if [ ${fname} != ${new_fname} ]; then
              echo "    ${new_fname} --> ${new_fname}"
              git "mv" "${fname}" ${new_fname}
            fi
          done
          git commit -am "formatting filenames ${GITHUB_SHA::8}" || true
