name: Golang
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang_lint_and_test:
    name: Code style and tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Run tests
        run: go test ./...
