name: lua-test
on: [push, pull_request]
jobs:s  
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: |
          sudo apt install luarocks -qyy
          sudo luarocks install luacheck
      - name: lint
        run: |
          luacheck ds
          luacheck .spec --config ./spec/.luacheckrc